# Generated by Django 3.2 on 2021-12-17 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0004_auto_20211215_1133'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shopuser',
            old_name='authentication_key',
            new_name='activation_key',
        ),
        migrations.RenameField(
            model_name='shopuser',
            old_name='authentication_key_expires',
            new_name='activation_key_expires',
        ),
    ]
