# Generated by Django 3.2 on 2022-02-05 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_auto_20220202_1250'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='quantity',
            new_name='quality',
        ),
    ]
